### ISSUE TITLE
Clear dist folder before build

### ISSUE THREAD

**Issue by JRJurman** [Tram-One/tram-one-express#58] opened 2019-02-27 05:39 UTC
## Summary

On Windows for generated projects, if doing multiple builds, extra files are generated inside of dist. Make sure this doesn't happen.

## Reproduction Steps
1. run `npm run build`
2. change some source file
3. run `npm run build` again

See below where two sets of js and css files are built in the dist directory, but only one is referenced in the index.js
![image](https://user-images.githubusercontent.com/326557/66101868-5d91ff80-e57e-11e9-93b8-36b52333b19e.png)

This potentially requires investigation in how we use parceljs, and if other configurations are required.

**Comment by abhishekr700** [comment] 2019-10-13 19:43
Hi, do you just want the contents of the folder to be cleared before the build is started again ?

**Comment by JRJurman** [comment] 2019-10-13 20:03
@abhishekr700 potentially? I feel like this might be an error or a configuration missed with parceljs. I would prefer not to have a lot of custom functionality (and of course, anything that is there needs to work for both windows and mac.

**Comment by abhishekr700** [comment] 2019-10-13 20:44
@JRJurman That is not the case. What's happening is the intended behaviour. I've submitted a PR referencing the related issue and the fix.

**Comment by abhishekr700** [comment] 2019-10-14 07:53
@JRJurman I think we can close this issue now.

**Closed** 2019-10-14 13:15 UTC
Labels: easy, hacktoberfest
